<?php
$msquote = $block->getMsQuote();
$msquoteItems = $block->getMsQuoteItems($msquote->getEntityId());
?>
<?php if ($msquoteItems->count()>0) {?>
<main class="page-main">
    <div class="page-title-wrapper">
        <h1 class="page-title"><span class="base">RecurringOrder Cart</span></h1>
    </div>
    <div class="columns">
        <div class="column main">
            <div class="cart-container">
                <div class="cart-summary">
                    <strong class="summary title">Subscription Summary</strong>
                    <div id="subscription-cart-totals" class="cart-totals">
                        <div class="table-wrapper">
                            <table class="data table totals">
                                <caption class="table-caption">Total</caption>
                                <tbody>
                                    <tr class="totals sub">
                                        <th class="mark" scope="row">Subtotal</th>
                                        <td class="amount">
                                            <?= /* @noEscape */ $block->displayPrice($msquote->getSubtotal());?>
                                        </td>
                                    </tr>
                                    <!--<tr class="totals-tax">
                                        <th class="mark" colspan="1" scope="row">Tax</th>
                                        <td class="amount" data-th="Tax">
                                            <span class="price">$2.64</span>
                                        </td>
                                    </tr>-->
                                    <tr class="grand totals">
                                        <th class="mark" scope="row">
                                            <strong>Subscription Order Total</strong>
                                        </th>
                                        <td class="amount" data-th="Subscription Order Total">
                                            <strong><?= /* @noEscape */ $block->displayPrice($msquote->getGrandTotal());?></strong>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <ul class="checkout methods items checkout-methods-items">
                        <li class="item">    
                            <button onclick="loadSubscriptionPage()" type="button" data-role="proceed-to-checkout" title="Proceed to Checkout" class="action primary checkout">
                                <span>Proceed to Subscription</span>
                            </button>
                        </li>
                    </ul>
                </div>
                <form class="form form-cart" action="<?= /* @noEscape */ $block->getUrl('RecurringOrder/index/update/')?>" method="POST">
                    <div class="cart table-wrapper">
                        <table class="cart items data table">
                            <thead>
                                <tr>
                                    <th class="col item" scope="col"><span>Item</span></th>
                                    <th class="col price" scope="col"><span>Price</span></th>
                                    <th class="col qty" scope="col"><span>Qty</span></th>
                                    <th class="col subtotal" scope="col"><span>Subtotal</span></th>
                                </tr>
                            </thead>
                            <?php foreach ($msquoteItems as $item) {?>
                                <tbody class="cart item">
                                    <tr class="item-info">
                                        <td data-th="Item" class="col item">
                                            <a href="<?= $block->escapeUrl($item->getUrl())?>" title="<?= /* @noEscape */ $item->getName()?>" tabindex="-1" class="product-item-photo"><span class="product-image-container" style="width:165px;"><span class="product-image-wrapper" style="padding-bottom: 100%;"><img class="product-image-photo" src="<?= /* @noEscape */ $item->getImage()?>" alt="<?= /* @noEscape */ $item->getName()?>" height="165" width="165"></span></span></a>
                                            <div class="product-item-details">
                                                <strong class="product-item-name">
                                                    <a href="<?= /* @noEscape */ $item->getUrl()?>"><?= /* @noEscape */ $item->getName()?></a>
                                                </strong>
                                            </div>
                                        </td>
                                        <td class="col price" data-th="Price">
                                                <span class="price-excluding-tax" data-label="Excl. Tax">
                                                        <span class="cart-price"><?= /* @noEscape */ $block->displayPrice($item->getPrice())?></span>
                                                </span>
                                        </td>
                                        <td class="col qty" data-th="Qty">
                                            <div class="field qty">
                                                <label class="label" for="cart-<?=  /* @noEscape */ $item->getId()?>-qty">
                                                    <span>Qty</span>
                                                </label>
                                                <div class="control qty">
                                                    <input id="cart-<?= /* @noEscape */ $item->getId()?>-qty" name="cart[<?= /* @noEscape */ $item->getId()?>][qty]" value="<?= /* @noEscape */ $item->getQty()?>" size="4" title="Qty" class="input-text qty" type="number">
                                                </div>
                                            </div>
                                        </td>
                                        <td class="col subtotal" data-th="Subtotal">           
                                            <span class="price-excluding-tax" data-label="Excl. Tax">
                                                    <span class="cart-price"><?= /* @noEscape */ $block->displayPrice($item->getRowTotal())?></span>
                                            </span>
                                        </td>
                                    </tr>
                                    <tr class="item-actions">
                                        <td colspan="100">
                                            <div class="actions-toolbar">
                                            <a href="<?= $block->escapeUrl($block->getUrl('RecurringOrder/index/delete/id/'.$item->getId()))?>" title="Remove item" class="action action-delete">
                                                <span>Remove item</span>
                                            </a>
                                            </div>
                                        </td>
                                    </tr>
                                </tbody>
                            <?php }?>
                        </table>
                    </div>
                    <div class="cart main actions">
                        <button type="submit" name="update_subscription_action" data-cart-item-update="" value="update_qty" title="Update Subscription Cart" class="action update">
                            <span>Update RecurringOrder Cart</span>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>
<script type="text/javascript">
    function loadSubscriptionPage(){
        window.location="<?= $block->escapeUrl($block->getUrl('RecurringOrder')) ?>"
    }
</script>
<?php }?>