<?php
$numColumns = sizeof($block->getColumns());
?>
<?php if ($block->getCollection()): ?>

    <?php if ($block->canDisplayContainer()): ?>
<div id="<?= $escaper->escapeHtml($block->getId()) ?>" data-grid-id="<?= $escaper->escapeHtml($block->getId()) ?>">
<?php else: ?>
    <?= $block->getLayout()->getMessagesBlock()->getGroupedHtml() ?>
<?php endif; ?>
        <div class="admin__data-grid-wrap admin__data-grid-wrap-static">
        <?php if ($block->getGridCssClass()): ?>
            <table class="<?= /* @escapeNotVerified */ $block->getGridCssClass() ?> data-grid" id="<?= $escaper->escapeHtml($block->getId()) ?>_table">
                <!-- Rendering column set -->
                <?= $block->getChildHtml('grid.columnSet') ?>
            </table>
        <?php else: ?>

            <table class="data-grid" id="<?= $escaper->escapeHtml($block->getId()) ?>_table">
                <!-- Rendering column set -->
                <?= $block->getChildHtml('grid.columnSet') ?>
            </table>

            <?php if ($block->getChildBlock('grid.bottom.links')): ?>
                <?= $block->getChildHtml('grid.bottom.links') ?>
            <?php endif; ?>

        <?php endif ?>
        </div>
    <?php if ($block->canDisplayContainer()): ?>
</div>
<script>
    var deps = [];

        <?php if ($block->getDependencyJsObject()): ?>
    deps.push('uiRegistry');
    <?php endif; ?>

        <?php if (strpos($block->getRowClickCallback(), 'order.') !== false): ?>
    deps.push('Magento_Sales/order/create/form');
    deps.push('jquery');
    <?php endif; ?>

    deps.push('mage/adminhtml/grid');

    require(deps, function(<?= ($block->getDependencyJsObject() ? 'registry' : '') ?>){
        <?php //TODO: getJsObjectName and getRowClickCallback has unexpected behavior. Should be removed ?>

        <?php if ($block->getDependencyJsObject()): ?>
            registry.get('<?= /* @escapeNotVerified */ $block->getDependencyJsObject() ?>', function (<?= /* @escapeNotVerified */ $block->getDependencyJsObject() ?>) {
        <?php endif; ?>

        <?= /* @escapeNotVerified */ $block->getJsObjectName() ?> = new varienGrid('<?= $escaper->escapeHtml($block->getId()) ?>', '<?= /* @escapeNotVerified */ $block->getGridUrl() ?>', '<?= /* @escapeNotVerified */ $block->getVarNamePage() ?>', '<?= /* @escapeNotVerified */ $block->getVarNameSort() ?>', '<?= /* @escapeNotVerified */ $block->getVarNameDir() ?>', '<?= /* @escapeNotVerified */ $block->getVarNameFilter() ?>');
        <?= /* @escapeNotVerified */ $block->getJsObjectName() ?>.useAjax = <?= /* @escapeNotVerified */ $block->getUseAjax() ? 'true' : 'false' ?>;
        <?php if ($block->getRowClickCallback()): ?>
            <?= /* @escapeNotVerified */ $block->getJsObjectName() ?>.rowClickCallback = <?= /* @escapeNotVerified */ $block->getRowClickCallback() ?>;
        <?php endif; ?>
        <?php if ($block->getCheckboxCheckCallback()): ?>
            <?= /* @escapeNotVerified */ $block->getJsObjectName() ?>.checkboxCheckCallback = <?= /* @escapeNotVerified */ $block->getCheckboxCheckCallback() ?>;
        <?php endif; ?>
        <?php if ($block->getSortableUpdateCallback()): ?>
            <?= /* @escapeNotVerified */ $block->getJsObjectName() ?>.sortableUpdateCallback = <?= /* @escapeNotVerified */ $block->getSortableUpdateCallback() ?>;
        <?php endif; ?>
        <?= /* @escapeNotVerified */ $block->getJsObjectName() ?>.bindSortable();
        <?php if ($block->getRowInitCallback()): ?>
            <?= /* @escapeNotVerified */ $block->getJsObjectName() ?>.initRowCallback = <?= /* @escapeNotVerified */ $block->getRowInitCallback() ?>;
            <?= /* @escapeNotVerified */ $block->getJsObjectName() ?>.initGridRows();
        <?php endif; ?>
        <?php if ($block->getChildBlock('grid.massaction') && $block->getChildBlock('grid.massaction')->isAvailable()): ?>
            <?= /* @escapeNotVerified */ $block->getChildBlock('grid.massaction')->getJavaScript() ?>
        <?php endif ?>
        <?= /* @escapeNotVerified */ $block->getAdditionalJavaScript() ?>

        <?php if ($block->getDependencyJsObject()): ?>
            });
        <?php endif; ?>
    });
</script>
<?php endif; ?>

    <?php if ($block->getChildBlock('grid.js')): ?>
        <?= $block->getChildHtml('grid.js') ?>
<?php endif; ?>

<?php endif ?>

